spring.application.name=EmployeeManagement

spring.profiles.active=dev
#this file only say->
#Run using Development configuration.
#Eclipse → you can explicitly run with the dev profile if needed.
#Docker → will definitely use SPRING_PROFILES_ACTIVE=docker