spring.application.name=EmployeeManagement

spring.datasource.url=jdbc:mysql://localhost:3306/employeemanagement
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
file.upload-dir=uploads


#for redius

spring.data.redis.host=localhost
spring.data.redis.port=6379
#----------------------------------
#debug=true
#ddl-auto=update-> auto create tables
#show-sql=true->shows sql queries in console

#//Feign Client reduces boilerplate code because we only define interfaces.
# It integrates well with service discovery, load balancing, and circuit breakers, 
#so it is preferred in microservice architectures.